name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted

    container:
      image: gcr.io/bazel-public/bazel:latest
      # or use a local Dockerfile build by GitHub Actions
      # image: my-bazel-image
      options: --user 1001
      
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo hostname
        echo "i am running on local machine hostname : $hostname "
        printenv

    - name: Check Bazel version
      run: bazel --version

    - name: Check Bazel version
      run: bazel build //...

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t my-bazel-image .
      - name: Run build inside container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace my-bazel-image bazel --version
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace my-bazel-image bazel build //...
          
 
 
